// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTM6jWDAX3KBn3qIftR110NbHLHGRrHvo',
    appId: '1:293101875477:web:c6627172ff068c67ffb91c',
    messagingSenderId: '293101875477',
    projectId: 'assignment5-maps-d859a',
    authDomain: 'assignment5-maps-d859a.firebaseapp.com',
    storageBucket: 'assignment5-maps-d859a.appspot.com',
    measurementId: 'G-JDGNDVF82E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0EES_wlXBiyNPgUctoS7dpaB5_OGG9Qw',
    appId: '1:293101875477:android:f28178442ae12e3effb91c',
    messagingSenderId: '293101875477',
    projectId: 'assignment5-maps-d859a',
    storageBucket: 'assignment5-maps-d859a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlikF4ETMVN5V5XC1x9WdwnBCOtW29v3s',
    appId: '1:293101875477:ios:e099392229010c17ffb91c',
    messagingSenderId: '293101875477',
    projectId: 'assignment5-maps-d859a',
    storageBucket: 'assignment5-maps-d859a.appspot.com',
    iosClientId: '293101875477-nj8jfasgknq4cea9rifsd5uqddcot19u.apps.googleusercontent.com',
    iosBundleId: 'com.example.assignment5MapsFirebase',
  );
}
